"""
Django settings.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'

TIME_ZONE = 'UTC'

##############################
#          WARNING!          #
#         IN SECONDS         #
##############################
TIMEOUTS = {
    'VERIFICATION_CODE': 60 * 10,
    'PASSWORD_RESET_LINK': 60 * 30,
    'REDIS_CACHES': 60 * 60 * 24 * 30,
    'OAUTH_STATE': 60 * 10,
}

ADMIN_URL = os.environ.get('DJANGO_ADMIN_URL')
ADMIN_IPS = []
ALLOWED_HOSTS = [
    'localhost', # for dev
    '127.0.0.1', # for dev
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000', # for dev
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000', # for dev
]

CLIENT_BASE_URL = 'http://127.0.0.1:3000' # without lslash
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_ALWAYS_EAGER = DEBUG

AUTH_USER_MODEL = 'accounts.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@greenhabit.ru'

ERROR_DETAIL_KEY = 'detail'
TRAILING_PUNCT_PATTERN = r'[.!?…]+$'

PASSWORD_RESET_TIMEOUT = TIMEOUTS['PASSWORD_RESET_LINK']

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

REFRESH_ROTATION_GRACE_SECONDS = 60
REFRESH_GRACE_SECRET = os.environ.get('REFRESH_GRACE_SECRET')

DEFAULT_USERNAME_PREFIX = 'user'

USERNAME_CHANGE_LIMIT = 3
USERNAME_CHANGE_WINDOW_DAYS = 30

if not DEBUG:
    CLIENT_BASE_URL = os.environ.get('CLIENT_URL')
    CORS_ALLOWED_ORIGINS.append(CLIENT_BASE_URL)
    CSRF_TRUSTED_ORIGINS.append(CLIENT_BASE_URL)

    ALLOWED_HOSTS.append(os.environ.get('DJANGO_HOST'))
    ADMIN_IPS.append(os.environ.get('DJANGO_ADMIN_IP'))

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'

    CELERY_RESULT_BACKEND = (os.environ.get('CELERY_RESULT_BACKEND'))
    CELERY_BROKER_URL = (os.environ.get('CELERY_BROKER_URL'))
    CELERY_ACKS_LATE = True

    EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
    ANYMAIL = {
        'BREVO_API_KEY': os.environ.get('EMAIL_API_KEY'),
        'IGNORE_RECIPIENT_STATUS': True,
    }

    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',

        'LOCATION': os.getenv('CACHE_BROKER_URL'),
        'TIMEOUT': TIMEOUTS['REDIS_CACHES'],
    }

##############################
#          WARNING!          #
#       WITHOUT LSLASH       #
##############################
CLIENT_ENDPOINTS = {
    'PASSWORD_RESET': f'{CLIENT_BASE_URL.rstrip('/')}/auth/password/reset',
}

# Application definition
INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'anymail',
]

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'core.exception_handlers.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'resend_code': '1/minute',
        'login': '10/hour',
        'register': '10/hour',
        'email_confirm': '10/hour',
        'reset_password': '5/hour',
        'password_reset_confirm': '10/hour',
        'validate_reset_token': '10/minute',
        'oauth_start': '30/hour',
        'oauth_callback': '60/hour',
        'update_username': '20/minute',
    }
}

SIMPLE_JWT = {
    'REFRESH_COOKIE': 'refresh_token',
    'AUTH_COOKIE': 'access_token',
    'REFRESH_COOKIE_HTTP_ONLY': True,
    'REFRESH_COOKIE_SAMESITE': 'None',
    'REFRESH_COOKIE_SECURE': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}


OAUTH_CLIENTS = {
    'github': {
        'client_id': os.getenv('GITHUB_CLIENT_ID'),
        'client_secret': os.getenv('GITHUB_CLIENT_SECRET'),
        'access_token_url': 'https://github.com/login/oauth/access_token',
        'authorize_url': 'https://github.com/login/oauth/authorize',
        'api_base_url': 'https://api.github.com',
        'scope': 'read:user user:email',
    },
    'x': {
        'client_id': os.getenv('X_CLIENT_ID'),
        'client_secret': os.getenv('X_CLIENT_SECRET'),
        'access_token_url': 'https://api.x.com/2/oauth2/token',
        'authorize_url': 'https://x.com/i/oauth2/authorize',
        'api_base_url': 'https://api.x.com/2',
        'scope': 'users.read tweet.read',
    },
    'google': {
        'client_id': os.getenv('GOOGLE_CLIENT_ID'),
        'client_secret': os.getenv('GOOGLE_CLIENT_SECRET'),
        'access_token_url': 'https://oauth2.googleapis.com/token',
        'authorize_url': 'https://accounts.google.com/o/oauth2/v2/auth',
        'api_base_url': 'https://openidconnect.googleapis.com',
        'scope': 'openid email profile',
    },
    'yandex': {
        'client_id': os.getenv('YANDEX_CLIENT_ID'),
        'client_secret': os.getenv('YANDEX_CLIENT_SECRET'),
        'access_token_url': 'https://oauth.yandex.ru/token',
        'authorize_url': 'https://oauth.yandex.ru/authorize',
        'api_base_url': 'https://login.yandex.ru',
        'scope': 'login:email login:info',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AdminIPRestrictionMiddleware',
    'djangorestframework_camel_case.middleware.CamelCaseMiddleWare',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = True

DEFAULT_HUMAN_DATETIME_FORMAT = '%d.%m.%Y %H:%M:%S %Z'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'